### ISSUE TITLE
building image: ValueError: @jupyterlab/celltags" is not a valid extension

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_custom_ai_platform_notebook#1]
Step #7 - "Build the Docker image": npm notice name:          @jupyterlab/celltags                    
Step #7 - "Build the Docker image": npm notice version:       2.0.0                                   
Step #7 - "Build the Docker image": npm notice filename:      jupyterlab-celltags-2.0.0.tgz           
Step #7 - "Build the Docker image": npm notice package size:  6.1 kB                                  
Step #7 - "Build the Docker image": npm notice unpacked size: 26.2 kB                                 
Step #7 - "Build the Docker image": npm notice shasum:        1b73e15fa4eb5f44db07581be4df0df508ae5373
Step #7 - "Build the Docker image": npm notice integrity:     sha512-qwD+Yfw/4Busr[...]IzfH0k93Nr5YQ==
Step #7 - "Build the Docker image": npm notice total files:   13                                      
Step #7 - "Build the Docker image": npm notice 
Step #7 - "Build the Docker image": jupyterlab-celltags-2.0.0.tgz
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image": Traceback (most recent call last):
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image":   File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
Step #7 - "Build the Docker image":     yield
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image":   File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 93, in start
Step #7 - "Build the Docker image":     ans = self.run_task()
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image":   File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 149, in run_task
Step #7 - "Build the Docker image":     for i, arg in enumerate(self.extra_args)
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image":   File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 149, in <listcomp>
Step #7 - "Build the Docker image":     for i, arg in enumerate(self.extra_args)
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image":   File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/commands.py", line 398, in install_extension
Step #7 - "Build the Docker image":     return handler.install_extension(extension, pin=pin)
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image":   File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/commands.py", line 611, in install_extension
Step #7 - "Build the Docker image":     info = self._install_extension(extension, tempdir, pin=pin)
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image":   File "/opt/conda/envs/jupyter-notebook/lib/python3.7/site-packages/jupyterlab/commands.py", line 1514, in _install_extension
Step #7 - "Build the Docker image":     raise ValueError(msg % (extension, '\n'.join(messages)))
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image": ValueError: "@jupyterlab/celltags" is not a valid extension:
Step #7 - "Build the Docker image": No `jupyterlab` key
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image": Exiting application: jupyter
Step #7 - "Build the Docker image": 
Step #7 - "Build the Docker image": -\|/-\|/-\|/-\|/An error occured.
Step #7 - "Build the Docker image": ValueError: "@jupyterlab/celltags" is not a valid extension:
Step #7 - "Build the Docker image": No `jupyterlab` key
Step #7 - "Build the Docker image": See the log file for details:  /tmp/jupyterlab-debug-65zpfbhp.log

**Comment by tarrade** [comment]
@jupyterlab/celltags 2.00 is installe dby default with JupyerLab 2.0.0

The issue is many extension doesn't work with the new version of Jupyter Lab

Using the previous version 0.2.0 and it works
