### ISSUE TITLE
Error in loading extension: sql

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_custom_ai_platform_notebook#4]
```
[IPKernelApp] WARNING | Error in loading extension: sql
Check your config files in /root/.ipython/profile_default
Traceback (most recent call last):
  File "/home/.conda-env/env_multilingual_class/lib/python3.7/site-packages/IPython/core/shellapp.py", line 261, in 
init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/home/.conda-env/env_multilingual_class/lib/python3.7/site-packages/IPython/core/extensions.py", line 80, in
 load_extension
    mod = import_module(module_str)
  File "/home/.conda-env/env_multilingual_class/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sql'
```

this is coming from:
```
 cat /root/.ipython/profile_default/ipython_kernel_config.py
c.IPKernelApp.extensions = [ 'google.cloud.bigquery', 'sql'] 
```

this package was installed in the based but doesn't solve the issue:
`ipython-sql=0.3.9`

**Comment by tarrade** [comment]
instead of using GCP based image, I started from scratch and all the side effect confi related to the GCP based imaged are gone.
